
// ------------ CITIES
export const RECEIVE_DETAILS_CITY = "RECEIVE_DETAILS_CITY"
export const RECEIVE_CITIES = "RECEIVE_CITIES"
export const ADD_CITY_GROUP = "ADD_CITY_GROUP"

// ------------ USER PARAMS
export const RECEIVE_USER_PARAMS = "RECEIVE_USER_PARAMS"

// ------------ OPEN WEATHER CITIES
export const RECEIVE_SEARCH_CITIES = "RECEIVE_SEARCH_CITIES"
export const REINIT_SEARCHED_CITIES = "REINIT_SEARCHED_CITIES"

// ------------ USER CITIES
export const ADD_CITY = "ADD_CITY"

